/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: ee36a788b9e274627763f5ec3a57b516)
interface __BaseEnv_Env {
	BLOBS: R2Bucket;
	AUTH_MODE: "scaffold" | "dev";
	ENVIRONMENT: "staging" | "production" | "local";
	APNS_TOPIC?: "ai.ashler.crew.staging" | "ai.ashler.crew";
	APNS_TEAM_ID?: "825LYXGJR6";
	SCAFFOLD_CONTROL_PLANE_URL: "https://scaffold-staging.internal.ashler.com" | "https://scaffold.internal.ashler.com" | "http://127.0.0.1:8788";
	SCAFFOLD_PROJECT_SCOPE: "ashler-staging" | "ashler-production" | "ashler-local";
	SCAFFOLD_REQUIRED_CAPABILITIES: "session.read session.chat session.control session.annotate session.invite session.files session.environment";
	SESSION_ROOMS: DurableObjectNamespace<import("./src/index").SessionRoom>;
	DEVICE_ROOMS: DurableObjectNamespace<import("./src/index").DeviceRoom>;
	AUTH_GRANTS: DurableObjectNamespace<import("./src/index").AuthGrant>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "SessionRoom" | "DeviceRoom" | "AuthGrant";
	}
	interface StagingEnv {
		BLOBS: R2Bucket;
		AUTH_MODE: "scaffold";
		ENVIRONMENT: "staging";
		APNS_TOPIC: "ai.ashler.crew.staging";
		APNS_TEAM_ID: "825LYXGJR6";
		SCAFFOLD_CONTROL_PLANE_URL: "https://scaffold-staging.internal.ashler.com";
		SCAFFOLD_PROJECT_SCOPE: "ashler-staging";
		SCAFFOLD_REQUIRED_CAPABILITIES: "session.read session.chat session.control session.annotate session.invite session.files session.environment";
		SESSION_ROOMS: DurableObjectNamespace<import("./src/index").SessionRoom>;
		DEVICE_ROOMS: DurableObjectNamespace<import("./src/index").DeviceRoom>;
		AUTH_GRANTS: DurableObjectNamespace<import("./src/index").AuthGrant>;
	}
	interface ProductionEnv {
		BLOBS: R2Bucket;
		AUTH_MODE: "scaffold";
		ENVIRONMENT: "production";
		APNS_TOPIC: "ai.ashler.crew";
		APNS_TEAM_ID: "825LYXGJR6";
		SCAFFOLD_CONTROL_PLANE_URL: "https://scaffold.internal.ashler.com";
		SCAFFOLD_PROJECT_SCOPE: "ashler-production";
		SCAFFOLD_REQUIRED_CAPABILITIES: "session.read session.chat session.control session.annotate session.invite session.files session.environment";
		SESSION_ROOMS: DurableObjectNamespace<import("./src/index").SessionRoom>;
		DEVICE_ROOMS: DurableObjectNamespace<import("./src/index").DeviceRoom>;
		AUTH_GRANTS: DurableObjectNamespace<import("./src/index").AuthGrant>;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AUTH_MODE" | "ENVIRONMENT" | "APNS_TOPIC" | "APNS_TEAM_ID" | "SCAFFOLD_CONTROL_PLANE_URL" | "SCAFFOLD_PROJECT_SCOPE" | "SCAFFOLD_REQUIRED_CAPABILITIES">> {}
}
